spring:
  datasource:
      url: jdbc:mysql://localhost:3306/studentdatabase
      username:  root
      password: Selina$123
  jpa:
    hibernate:
      ddl-auto: update
 
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      


  
      